import type { Archetype } from "./types";

// M3 fixture slice (operator selected 8 archetypes).
export const archetypes: Archetype[] = [
  {
    key: "mage_frost_safe",
    classId: "mage",
    faction: "either",
    title: "Frost Survivor",
    subline: "Safe path · control first",
    tier: "safe",
    tags: ["safe", "control", "solo", "escape_tools", "no_pet"],
    safetyMechanism: "Root + blink spacing",
    first10: ["Frostbolt cadence", "Wand discipline", "Never chain two equal-level packs"],
  },
  {
    key: "hunter_bm_safe",
    classId: "hunter",
    faction: "either",
    title: "Beastmaster Route",
    subline: "Safe path · pet buffer",
    tier: "safe",
    tags: ["safe", "pet", "solo", "steady", "new_player"],
    safetyMechanism: "Pet aggro buffer + traps",
    first10: ["Pull through pet", "Bandage cadence", "Ammo checks before route"],
  },
  {
    key: "warrior_arms_safe",
    classId: "warrior",
    faction: "either",
    title: "Arms Tempered",
    subline: "Safe-ish path · strict pulls",
    tier: "safe",
    tags: ["safe", "melee", "discipline", "group_ok"],
    safetyMechanism: "Fight only advantaged pulls",
    first10: ["2H rhythm", "Hamstring exits", "Vendor weapon updates on schedule"],
  },
  {
    key: "warlock_affliction_safe",
    classId: "warlock",
    faction: "either",
    title: "Drain Tank Core",
    subline: "Safe path · attrition",
    tier: "safe",
    tags: ["safe", "solo", "pet", "sustain"],
    safetyMechanism: "Fear pathing + drain sustain",
    first10: ["DoT then kite", "Pet stance discipline", "Pull spacing over speed"],
  },
  {
    key: "rogue_combat_off_beaten",
    classId: "rogue",
    faction: "either",
    title: "Combat Route",
    subline: "Off the beaten path · controlled aggression",
    tier: "off_beaten",
    tags: ["off_beaten", "fast", "melee", "solo", "no_pet"],
    safetyMechanism: "Vanish reserve and reset windows",
    first10: ["Open only isolated targets", "Sprint for disengage not chase", "Poison uptime discipline"],
  },
  {
    key: "priest_shadow_safe",
    classId: "priest",
    faction: "either",
    title: "Shadow Spirit Tap",
    subline: "Safe path · wand economy",
    tier: "safe",
    tags: ["safe", "caster", "solo", "steady", "group_ok"],
    safetyMechanism: "Fear + shield pacing",
    first10: ["Wand finish for mana", "Shield before panic", "Never overpull indoors"],
  },
  {
    key: "druid_feral_off_beaten",
    classId: "druid",
    faction: "either",
    title: "Feral Wanderer",
    subline: "Off the beaten path · tempo flexibility",
    tier: "off_beaten",
    tags: ["off_beaten", "solo", "versatile", "steady"],
    safetyMechanism: "Form swap exits",
    first10: ["Travel tempo over combat greed", "Form swap for reset", "Quest density over raw XP race"],
  },
  {
    key: "shaman_enhancement_safe",
    classId: "shaman",
    faction: "horde",
    title: "Enhancement Windfury",
    subline: "Safe path · horde utility",
    tier: "safe",
    tags: ["safe", "horde_only", "melee", "totem", "group_ok"],
    safetyMechanism: "Totem control and shield pivots",
    first10: ["Totem cadence", "Shield swap for danger pulls", "Weapon buff uptime"],
  },
];

export const classFactionMap: Record<string, "either" | "horde" | "alliance"> = {
  mage: "either",
  hunter: "either",
  warrior: "either",
  warlock: "either",
  priest: "either",
  rogue: "either",
  druid: "either",
  paladin: "alliance",
  shaman: "horde",
};
