import type { ClassTalents } from "./types";

export const hunterTalents: ClassTalents = {
  classId: "hunter",
  trees: [
    {
      branch: "Beast Mastery",
      slug: "beastmastery",
      talents: [
        { id: "bm.improved_aspect_of_the_monkey", name: "Improved Aspect of the Monkey", iconKey: "aspect_monkey", tier: 1, column: 2, maxRank: 5 },
        { id: "bm.endurance_training", name: "Endurance Training", iconKey: "endurance_training", tier: 1, column: 3, maxRank: 5 },
        { id: "bm.improved_eyes_of_the_beast", name: "Improved Eyes of the Beast", iconKey: "eyes_beast", tier: 2, column: 1, maxRank: 2 },
        { id: "bm.improved_aspect_of_the_hawk", name: "Improved Aspect of the Hawk", aliases: ["imp hawk"], iconKey: "aspect_hawk", tier: 2, column: 2, maxRank: 5 },
        { id: "bm.unleashed_fury", name: "Unleashed Fury", iconKey: "unleashed_fury", tier: 2, column: 3, maxRank: 5 },
        { id: "bm.improved_revive_pet", name: "Improved Revive Pet", iconKey: "revive_pet", tier: 3, column: 1, maxRank: 2 },
        { id: "bm.pathfinding", name: "Pathfinding", iconKey: "pathfinding", tier: 3, column: 2, maxRank: 2 },
        { id: "bm.bestial_swiftness", name: "Bestial Swiftness", iconKey: "bestial_swiftness", tier: 3, column: 3, maxRank: 1 },
        { id: "bm.ferocity", name: "Ferocity", iconKey: "ferocity_hunter", tier: 4, column: 1, maxRank: 5 },
        { id: "bm.spirit_bond", name: "Spirit Bond", iconKey: "spirit_bond", tier: 4, column: 2, maxRank: 2 },
        { id: "bm.intimidation", name: "Intimidation", iconKey: "intimidation", tier: 4, column: 3, maxRank: 1 },
        { id: "bm.bestial_discipline", name: "Bestial Discipline", iconKey: "bestial_discipline", tier: 5, column: 1, maxRank: 2 },
        { id: "bm.frenzy", name: "Frenzy", iconKey: "frenzy", tier: 5, column: 3, maxRank: 5 },
        { id: "bm.bestial_wrath", name: "Bestial Wrath", aliases: ["bw"], iconKey: "bestial_wrath", tier: 6, column: 2, maxRank: 1, prereqId: "bm.intimidation" },
      ],
    },
    {
      branch: "Marksmanship",
      slug: "marksmanship",
      talents: [
        { id: "mm.improved_concussive_shot", name: "Improved Concussive Shot", iconKey: "concussive_shot", tier: 1, column: 2, maxRank: 5 },
        { id: "mm.efficiency", name: "Efficiency", iconKey: "efficiency", tier: 1, column: 3, maxRank: 5 },
        { id: "mm.improved_hunters_mark", name: "Improved Hunter's Mark", aliases: ["imp hunters mark"], iconKey: "hunters_mark", tier: 2, column: 1, maxRank: 5 },
        { id: "mm.lethal_shots", name: "Lethal Shots", iconKey: "lethal_shots", tier: 2, column: 2, maxRank: 5 },
        { id: "mm.aimed_shot", name: "Aimed Shot", iconKey: "aimed_shot", tier: 2, column: 3, maxRank: 1 },
        { id: "mm.improved_arcane_shot", name: "Improved Arcane Shot", iconKey: "arcane_shot", tier: 3, column: 1, maxRank: 5 },
        { id: "mm.hawk_eye", name: "Hawk Eye", iconKey: "hawk_eye", tier: 3, column: 2, maxRank: 3 },
        { id: "mm.improved_serpent_sting", name: "Improved Serpent Sting", iconKey: "serpent_sting", tier: 3, column: 3, maxRank: 5 },
        { id: "mm.mortal_shots", name: "Mortal Shots", iconKey: "mortal_shots", tier: 4, column: 2, maxRank: 5 },
        { id: "mm.scatter_shot", name: "Scatter Shot", iconKey: "scatter_shot", tier: 4, column: 3, maxRank: 1 },
        { id: "mm.barrage", name: "Barrage", iconKey: "barrage", tier: 5, column: 2, maxRank: 3 },
        { id: "mm.ranged_weapon_specialization", name: "Ranged Weapon Specialization", iconKey: "ranged_weapon_specialization", tier: 5, column: 3, maxRank: 5 },
        { id: "mm.trueshot_aura", name: "Trueshot Aura", iconKey: "trueshot_aura", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Survival",
      slug: "survival",
      talents: [
        { id: "surv.monster_slaying", name: "Monster Slaying", iconKey: "monster_slaying", tier: 1, column: 2, maxRank: 3 },
        { id: "surv.humanoid_slaying", name: "Humanoid Slaying", iconKey: "humanoid_slaying", tier: 1, column: 3, maxRank: 3 },
        { id: "surv.deflection", name: "Deflection", iconKey: "deflection", tier: 2, column: 1, maxRank: 5 },
        { id: "surv.entrapment", name: "Entrapment", iconKey: "entrapment", tier: 2, column: 2, maxRank: 5 },
        { id: "surv.savage_strikes", name: "Savage Strikes", iconKey: "savage_strikes", tier: 2, column: 3, maxRank: 2 },
        { id: "surv.improved_wing_clip", name: "Improved Wing Clip", aliases: ["imp wing clip"], iconKey: "wing_clip", tier: 3, column: 1, maxRank: 5 },
        { id: "surv.clever_traps", name: "Clever Traps", iconKey: "clever_traps", tier: 3, column: 2, maxRank: 2 },
        { id: "surv.survivalist", name: "Survivalist", iconKey: "survivalist", tier: 3, column: 3, maxRank: 5 },
        { id: "surv.deterrence", name: "Deterrence", iconKey: "deterrence", tier: 4, column: 1, maxRank: 1 },
        { id: "surv.trap_mastery", name: "Trap Mastery", iconKey: "trap_mastery", tier: 4, column: 2, maxRank: 3 },
        { id: "surv.surefooted", name: "Surefooted", iconKey: "surefooted", tier: 4, column: 3, maxRank: 3 },
        { id: "surv.improved_feign_death", name: "Improved Feign Death", aliases: ["imp feign death"], iconKey: "feign_death", tier: 5, column: 2, maxRank: 2 },
        { id: "surv.killer_instinct", name: "Killer Instinct", iconKey: "killer_instinct", tier: 5, column: 3, maxRank: 5 },
        { id: "surv.lightning_reflexes", name: "Lightning Reflexes", iconKey: "lightning_reflexes_hunter", tier: 6, column: 2, maxRank: 5 },
        { id: "surv.wyvern_sting", name: "Wyvern Sting", iconKey: "wyvern_sting", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
