import type { ClassTalents } from "./types";

export const mageTalents: ClassTalents = {
  classId: "mage",
  trees: [
    {
      branch: "Arcane",
      slug: "arcane",
      talents: [
        { id: "arcane.arcane_subtlety", name: "Arcane Subtlety", iconKey: "arcane_subtlety", tier: 1, column: 2, maxRank: 2 },
        { id: "arcane.arcane_focus", name: "Arcane Focus", iconKey: "arcane_focus", tier: 1, column: 3, maxRank: 5 },
        { id: "arcane.improved_arcane_missiles", name: "Improved Arcane Missiles", iconKey: "arcane_missiles", tier: 2, column: 1, maxRank: 5 },
        { id: "arcane.wand_specialization", name: "Wand Specialization", iconKey: "wand_specialization", tier: 2, column: 2, maxRank: 5 },
        { id: "arcane.magic_absorption", name: "Magic Absorption", iconKey: "magic_absorption", tier: 2, column: 3, maxRank: 5 },
        { id: "arcane.arcane_concentration", name: "Arcane Concentration", aliases: ["clearcasting"], iconKey: "arcane_concentration", tier: 3, column: 2, maxRank: 5 },
        { id: "arcane.magic_attunement", name: "Magic Attunement", iconKey: "magic_attunement", tier: 3, column: 3, maxRank: 2 },
        { id: "arcane.improved_arcane_explosion", name: "Improved Arcane Explosion", iconKey: "arcane_explosion", tier: 4, column: 1, maxRank: 3 },
        { id: "arcane.arcane_resilience", name: "Arcane Resilience", iconKey: "arcane_resilience", tier: 4, column: 2, maxRank: 1 },
        { id: "arcane.improved_mana_shield", name: "Improved Mana Shield", iconKey: "mana_shield", tier: 4, column: 3, maxRank: 2 },
        { id: "arcane.improved_counterspell", name: "Improved Counterspell", aliases: ["imp counterspell"], iconKey: "counterspell", tier: 5, column: 2, maxRank: 2 },
        { id: "arcane.arcane_meditation", name: "Arcane Meditation", iconKey: "arcane_meditation", tier: 5, column: 3, maxRank: 3 },
        { id: "arcane.presence_of_mind", name: "Presence of Mind", aliases: ["pom"], iconKey: "presence_of_mind", tier: 6, column: 2, maxRank: 1 },
        { id: "arcane.arcane_mind", name: "Arcane Mind", iconKey: "arcane_mind", tier: 6, column: 3, maxRank: 5 },
        { id: "arcane.arcane_instability", name: "Arcane Instability", iconKey: "arcane_instability", tier: 7, column: 1, maxRank: 3 },
        { id: "arcane.arcane_power", name: "Arcane Power", iconKey: "arcane_power", tier: 7, column: 2, maxRank: 1, prereqId: "arcane.presence_of_mind" },
      ],
    },
    {
      branch: "Fire",
      slug: "fire",
      talents: [
        { id: "fire.improved_fireball", name: "Improved Fireball", iconKey: "fireball", tier: 1, column: 2, maxRank: 5 },
        { id: "fire.impact", name: "Impact", iconKey: "impact", tier: 1, column: 3, maxRank: 5 },
        { id: "fire.ignite", name: "Ignite", iconKey: "ignite", tier: 2, column: 1, maxRank: 5 },
        { id: "fire.flame_throwing", name: "Flame Throwing", iconKey: "flame_throwing", tier: 2, column: 2, maxRank: 2 },
        { id: "fire.improved_fire_blast", name: "Improved Fire Blast", iconKey: "fire_blast", tier: 2, column: 3, maxRank: 3 },
        { id: "fire.incinerate", name: "Incinerate", iconKey: "incinerate", tier: 3, column: 1, maxRank: 2 },
        { id: "fire.improved_flamestrike", name: "Improved Flamestrike", iconKey: "flamestrike", tier: 3, column: 2, maxRank: 3 },
        { id: "fire.pyroblast", name: "Pyroblast", aliases: ["pyro"], iconKey: "pyroblast", tier: 3, column: 3, maxRank: 1 },
        { id: "fire.burning_soul", name: "Burning Soul", iconKey: "burning_soul", tier: 4, column: 1, maxRank: 2 },
        { id: "fire.improved_scorch", name: "Improved Scorch", aliases: ["imp scorch"], iconKey: "scorch", tier: 4, column: 2, maxRank: 3 },
        { id: "fire.improved_fire_ward", name: "Improved Fire Ward", iconKey: "fire_ward", tier: 4, column: 3, maxRank: 2 },
        { id: "fire.master_of_elements", name: "Master of Elements", aliases: ["moe"], iconKey: "master_of_elements", tier: 5, column: 1, maxRank: 3 },
        { id: "fire.critical_mass", name: "Critical Mass", iconKey: "critical_mass", tier: 5, column: 2, maxRank: 3 },
        { id: "fire.blast_wave", name: "Blast Wave", iconKey: "blast_wave", tier: 6, column: 1, maxRank: 1 },
        { id: "fire.fire_power", name: "Fire Power", iconKey: "fire_power", tier: 6, column: 3, maxRank: 5 },
        { id: "fire.combustion", name: "Combustion", iconKey: "combustion", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Frost",
      slug: "frost",
      talents: [
        { id: "frost.frost_warding", name: "Frost Warding", iconKey: "frost_ward", tier: 1, column: 2, maxRank: 2 },
        { id: "frost.improved_frostbolt", name: "Improved Frostbolt", iconKey: "frostbolt", tier: 1, column: 3, maxRank: 5 },
        { id: "frost.elemental_precision", name: "Elemental Precision", iconKey: "elemental_precision", tier: 2, column: 1, maxRank: 3 },
        { id: "frost.ice_shards", name: "Ice Shards", iconKey: "ice_shards", tier: 2, column: 2, maxRank: 5 },
        { id: "frost.frostbite", name: "Frostbite", iconKey: "frostbite", tier: 2, column: 3, maxRank: 5 },
        { id: "frost.improved_frost_nova", name: "Improved Frost Nova", iconKey: "frost_nova", tier: 3, column: 1, maxRank: 2 },
        { id: "frost.permafrost", name: "Permafrost", iconKey: "permafrost", tier: 3, column: 2, maxRank: 3 },
        { id: "frost.piercing_ice", name: "Piercing Ice", iconKey: "piercing_ice", tier: 3, column: 3, maxRank: 3 },
        { id: "frost.cold_snap", name: "Cold Snap", iconKey: "cold_snap", tier: 4, column: 1, maxRank: 1 },
        { id: "frost.improved_blizzard", name: "Improved Blizzard", iconKey: "blizzard", tier: 4, column: 2, maxRank: 3 },
        { id: "frost.arctic_reach", name: "Arctic Reach", iconKey: "arctic_reach", tier: 4, column: 3, maxRank: 2 },
        { id: "frost.frost_channeling", name: "Frost Channeling", iconKey: "frost_channeling", tier: 5, column: 1, maxRank: 3 },
        { id: "frost.shatter", name: "Shatter", iconKey: "shatter", tier: 5, column: 2, maxRank: 5 },
        { id: "frost.ice_block", name: "Ice Block", iconKey: "ice_block", tier: 6, column: 1, maxRank: 1 },
        { id: "frost.improved_cone_of_cold", name: "Improved Cone of Cold", iconKey: "cone_of_cold", tier: 6, column: 2, maxRank: 3 },
        { id: "frost.winters_chill", name: "Winter's Chill", iconKey: "winters_chill", tier: 6, column: 3, maxRank: 5 },
        { id: "frost.ice_barrier", name: "Ice Barrier", iconKey: "ice_barrier", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
