import type { ClassTalents } from "./types";

export const paladinTalents: ClassTalents = {
  classId: "paladin",
  trees: [
    {
      branch: "Holy",
      slug: "holy",
      talents: [
        { id: "holy.divine_strength", name: "Divine Strength", iconKey: "divine_strength", tier: 1, column: 2, maxRank: 5 },
        { id: "holy.divine_intellect", name: "Divine Intellect", iconKey: "divine_intellect", tier: 1, column: 3, maxRank: 5 },
        { id: "holy.spiritual_focus", name: "Spiritual Focus", iconKey: "spiritual_focus", tier: 2, column: 2, maxRank: 5 },
        { id: "holy.improved_seal_of_righteousness", name: "Improved Seal of Righteousness", aliases: ["imp sor"], iconKey: "seal_righteousness", tier: 2, column: 3, maxRank: 5 },
        { id: "holy.healing_light", name: "Healing Light", iconKey: "holy_light", tier: 3, column: 1, maxRank: 3 },
        { id: "holy.consecration", name: "Consecration", aliases: ["consec"], iconKey: "consecration", tier: 3, column: 2, maxRank: 1 },
        { id: "holy.improved_lay_on_hands", name: "Improved Lay on Hands", aliases: ["imp loh"], iconKey: "lay_on_hands", tier: 3, column: 3, maxRank: 2 },
        { id: "holy.unyielding_faith", name: "Unyielding Faith", iconKey: "unyielding_faith", tier: 4, column: 1, maxRank: 2 },
        { id: "holy.illumination", name: "Illumination", iconKey: "illumination", tier: 4, column: 2, maxRank: 5 },
        { id: "holy.improved_blessing_of_wisdom", name: "Improved Blessing of Wisdom", aliases: ["imp bow"], iconKey: "blessing_wisdom", tier: 4, column: 3, maxRank: 2 },
        { id: "holy.divine_favor", name: "Divine Favor", iconKey: "divine_favor", tier: 5, column: 2, maxRank: 1, prereqId: "holy.illumination" },
        { id: "holy.lasting_judgement", name: "Lasting Judgement", iconKey: "judgement", tier: 5, column: 3, maxRank: 3 },
        { id: "holy.holy_power", name: "Holy Power", iconKey: "holy_power", tier: 6, column: 2, maxRank: 5 },
        { id: "holy.holy_shock", name: "Holy Shock", iconKey: "holy_shock", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Protection",
      slug: "protection",
      talents: [
        { id: "prot.improved_devotion_aura", name: "Improved Devotion Aura", aliases: ["imp dev aura"], iconKey: "devotion_aura", tier: 1, column: 2, maxRank: 5 },
        { id: "prot.redoubt", name: "Redoubt", iconKey: "redoubt", tier: 1, column: 3, maxRank: 5 },
        { id: "prot.precision", name: "Precision", iconKey: "precision", tier: 2, column: 1, maxRank: 5 },
        { id: "prot.guardians_favor", name: "Guardian's Favor", iconKey: "guardians_favor", tier: 2, column: 2, maxRank: 2 },
        { id: "prot.toughness", name: "Toughness", iconKey: "toughness", tier: 2, column: 3, maxRank: 5 },
        { id: "prot.blessing_of_kings", name: "Blessing of Kings", aliases: ["bok", "kings"], iconKey: "blessing_of_kings", tier: 3, column: 2, maxRank: 1 },
        { id: "prot.improved_righteous_fury", name: "Improved Righteous Fury", iconKey: "righteous_fury", tier: 3, column: 3, maxRank: 3 },
        { id: "prot.shield_specialization", name: "Shield Specialization", iconKey: "shield_specialization", tier: 4, column: 1, maxRank: 5 },
        { id: "prot.anticipation", name: "Anticipation", iconKey: "anticipation", tier: 4, column: 3, maxRank: 5 },
        { id: "prot.improved_hammer_of_justice", name: "Improved Hammer of Justice", aliases: ["imp hoj"], iconKey: "hammer_of_justice", tier: 5, column: 1, maxRank: 3 },
        { id: "prot.improved_concentration_aura", name: "Improved Concentration Aura", iconKey: "concentration_aura", tier: 5, column: 2, maxRank: 3 },
        { id: "prot.blessing_of_sanctuary", name: "Blessing of Sanctuary", aliases: ["bos"], iconKey: "blessing_of_sanctuary", tier: 6, column: 2, maxRank: 1 },
        { id: "prot.reckoning", name: "Reckoning", iconKey: "reckoning", tier: 6, column: 3, maxRank: 5 },
        { id: "prot.holy_shield", name: "Holy Shield", iconKey: "holy_shield", tier: 7, column: 2, maxRank: 1, prereqId: "prot.blessing_of_sanctuary" },
      ],
    },
    {
      branch: "Retribution",
      slug: "retribution",
      talents: [
        { id: "ret.improved_blessing_of_might", name: "Improved Blessing of Might", aliases: ["imp bom"], iconKey: "blessing_might", tier: 1, column: 2, maxRank: 5 },
        { id: "ret.benediction", name: "Benediction", iconKey: "benediction_pally", tier: 1, column: 3, maxRank: 5 },
        { id: "ret.improved_judgement", name: "Improved Judgement", iconKey: "judgement", tier: 2, column: 1, maxRank: 2 },
        { id: "ret.improved_seal_of_the_crusader", name: "Improved Seal of the Crusader", iconKey: "seal_crusader", tier: 2, column: 2, maxRank: 3 },
        { id: "ret.deflection", name: "Deflection", iconKey: "deflection", tier: 2, column: 3, maxRank: 5 },
        { id: "ret.vindication", name: "Vindication", iconKey: "vindication", tier: 3, column: 1, maxRank: 3 },
        { id: "ret.conviction", name: "Conviction", iconKey: "conviction", tier: 3, column: 2, maxRank: 5 },
        { id: "ret.seal_of_command", name: "Seal of Command", aliases: ["soc"], iconKey: "seal_of_command", tier: 3, column: 3, maxRank: 1 },
        { id: "ret.pursuit_of_justice", name: "Pursuit of Justice", iconKey: "pursuit_of_justice", tier: 4, column: 1, maxRank: 2 },
        { id: "ret.eye_for_an_eye", name: "Eye for an Eye", iconKey: "eye_for_an_eye", tier: 4, column: 3, maxRank: 2 },
        { id: "ret.two_handed_weapon_specialization", name: "Two-Handed Weapon Specialization", aliases: ["two-handed weapon spec", "2h spec"], iconKey: "two_handed_weapon_specialization", tier: 5, column: 2, maxRank: 3 },
        { id: "ret.sanctity_aura", name: "Sanctity Aura", iconKey: "sanctity_aura", tier: 5, column: 3, maxRank: 1 },
        { id: "ret.vengeance", name: "Vengeance", iconKey: "vengeance_pally", tier: 6, column: 2, maxRank: 5 },
        { id: "ret.repentance", name: "Repentance", iconKey: "repentance", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
