import type { ClassTalents } from "./types";

export const priestTalents: ClassTalents = {
  classId: "priest",
  trees: [
    {
      branch: "Discipline",
      slug: "discipline",
      talents: [
        { id: "disc.unbreakable_will", name: "Unbreakable Will", iconKey: "unbreakable_will", tier: 1, column: 2, maxRank: 5 },
        { id: "disc.wand_specialization", name: "Wand Specialization", iconKey: "wand_specialization_priest", tier: 1, column: 3, maxRank: 5 },
        { id: "disc.silent_resolve", name: "Silent Resolve", iconKey: "silent_resolve", tier: 2, column: 1, maxRank: 5 },
        { id: "disc.improved_power_word_fortitude", name: "Improved Power Word: Fortitude", aliases: ["imp fort", "imp pwf"], iconKey: "power_word_fortitude", tier: 2, column: 2, maxRank: 2 },
        { id: "disc.improved_power_word_shield", name: "Improved Power Word: Shield", aliases: ["imp pws", "imp shield"], iconKey: "power_word_shield", tier: 2, column: 3, maxRank: 3 },
        { id: "disc.martyrdom", name: "Martyrdom", iconKey: "martyrdom", tier: 3, column: 1, maxRank: 2 },
        { id: "disc.inner_focus", name: "Inner Focus", iconKey: "inner_focus", tier: 3, column: 2, maxRank: 1 },
        { id: "disc.meditation", name: "Meditation", iconKey: "meditation", tier: 3, column: 3, maxRank: 3 },
        { id: "disc.improved_inner_fire", name: "Improved Inner Fire", iconKey: "inner_fire", tier: 4, column: 1, maxRank: 3 },
        { id: "disc.mental_agility", name: "Mental Agility", iconKey: "mental_agility", tier: 4, column: 2, maxRank: 5 },
        { id: "disc.improved_mana_burn", name: "Improved Mana Burn", iconKey: "mana_burn", tier: 4, column: 3, maxRank: 2 },
        { id: "disc.mental_strength", name: "Mental Strength", iconKey: "mental_strength", tier: 5, column: 2, maxRank: 5 },
        { id: "disc.divine_spirit", name: "Divine Spirit", iconKey: "divine_spirit", tier: 6, column: 2, maxRank: 1 },
        { id: "disc.power_infusion", name: "Power Infusion", aliases: ["pi"], iconKey: "power_infusion", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Holy",
      slug: "holy",
      talents: [
        { id: "holy.holy_specialization", name: "Holy Specialization", iconKey: "holy_specialization", tier: 1, column: 2, maxRank: 5 },
        { id: "holy.improved_renew", name: "Improved Renew", iconKey: "renew", tier: 2, column: 1, maxRank: 3 },
        { id: "holy.holy_nova", name: "Holy Nova", iconKey: "holy_nova", tier: 2, column: 2, maxRank: 1 },
        { id: "holy.divine_fury", name: "Divine Fury", iconKey: "divine_fury", tier: 2, column: 3, maxRank: 5 },
        { id: "holy.healing_focus", name: "Healing Focus", iconKey: "healing_focus", tier: 3, column: 2, maxRank: 5 },
        { id: "holy.improved_healing", name: "Improved Healing", iconKey: "improved_healing", tier: 3, column: 3, maxRank: 3 },
        { id: "holy.searing_light", name: "Searing Light", iconKey: "searing_light", tier: 4, column: 2, maxRank: 2 },
        { id: "holy.improved_prayer_of_healing", name: "Improved Prayer of Healing", iconKey: "prayer_of_healing", tier: 4, column: 3, maxRank: 2 },
        { id: "holy.spiritual_healing", name: "Spiritual Healing", iconKey: "spiritual_healing", tier: 5, column: 2, maxRank: 5 },
        { id: "holy.holy_reach", name: "Holy Reach", iconKey: "holy_reach", tier: 5, column: 3, maxRank: 2 },
        { id: "holy.improved_healing_light", name: "Improved Healing Light", iconKey: "greater_heal", tier: 6, column: 2, maxRank: 3 },
        { id: "holy.lightwell", name: "Lightwell", iconKey: "lightwell", tier: 6, column: 3, maxRank: 1 },
        { id: "holy.spiritual_guidance", name: "Spiritual Guidance", iconKey: "spiritual_guidance", tier: 7, column: 2, maxRank: 5 },
      ],
    },
    {
      branch: "Shadow",
      slug: "shadow",
      talents: [
        { id: "shadow.spirit_tap", name: "Spirit Tap", iconKey: "spirit_tap", tier: 1, column: 2, maxRank: 5 },
        { id: "shadow.blackout", name: "Blackout", iconKey: "blackout", tier: 1, column: 3, maxRank: 5 },
        { id: "shadow.shadow_affinity", name: "Shadow Affinity", iconKey: "shadow_affinity", tier: 2, column: 1, maxRank: 3 },
        { id: "shadow.improved_shadow_word_pain", name: "Improved Shadow Word: Pain", aliases: ["imp swp"], iconKey: "shadow_word_pain", tier: 2, column: 2, maxRank: 2 },
        { id: "shadow.shadow_focus", name: "Shadow Focus", iconKey: "shadow_focus", tier: 2, column: 3, maxRank: 5 },
        { id: "shadow.improved_psychic_scream", name: "Improved Psychic Scream", aliases: ["imp ps"], iconKey: "psychic_scream", tier: 3, column: 1, maxRank: 2 },
        { id: "shadow.improved_mind_blast", name: "Improved Mind Blast", iconKey: "mind_blast", tier: 3, column: 2, maxRank: 5 },
        { id: "shadow.mind_flay", name: "Mind Flay", aliases: ["mf"], iconKey: "mind_flay", tier: 3, column: 3, maxRank: 1 },
        { id: "shadow.improved_fade", name: "Improved Fade", iconKey: "fade", tier: 4, column: 1, maxRank: 2 },
        { id: "shadow.shadow_reach", name: "Shadow Reach", iconKey: "shadow_reach", tier: 4, column: 3, maxRank: 2 },
        { id: "shadow.shadow_weaving", name: "Shadow Weaving", iconKey: "shadow_weaving", tier: 5, column: 2, maxRank: 5 },
        { id: "shadow.silence", name: "Silence", iconKey: "silence", tier: 5, column: 3, maxRank: 1 },
        { id: "shadow.vampiric_embrace", name: "Vampiric Embrace", iconKey: "vampiric_embrace", tier: 6, column: 1, maxRank: 1 },
        { id: "shadow.darkness", name: "Darkness", iconKey: "darkness", tier: 6, column: 3, maxRank: 5 },
        { id: "shadow.shadowform", name: "Shadowform", iconKey: "shadowform", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
