import type { ClassTalents } from "./types";

export const rogueTalents: ClassTalents = {
  classId: "rogue",
  trees: [
    {
      branch: "Assassination",
      slug: "assassination",
      talents: [
        { id: "ass.improved_eviscerate", name: "Improved Eviscerate", iconKey: "eviscerate", tier: 1, column: 2, maxRank: 3 },
        { id: "ass.remorseless_attacks", name: "Remorseless Attacks", iconKey: "remorseless_attacks", tier: 1, column: 3, maxRank: 5 },
        { id: "ass.malice", name: "Malice", iconKey: "malice", tier: 2, column: 1, maxRank: 5 },
        { id: "ass.ruthlessness", name: "Ruthlessness", iconKey: "ruthlessness", tier: 2, column: 2, maxRank: 3 },
        { id: "ass.improved_slice_and_dice", name: "Improved Slice and Dice", aliases: ["imp snd"], iconKey: "slice_and_dice", tier: 2, column: 3, maxRank: 3 },
        { id: "ass.improved_expose_armor", name: "Improved Expose Armor", iconKey: "expose_armor", tier: 3, column: 1, maxRank: 2 },
        { id: "ass.lethality", name: "Lethality", iconKey: "lethality", tier: 3, column: 2, maxRank: 5 },
        { id: "ass.vile_poisons", name: "Vile Poisons", iconKey: "vile_poisons", tier: 4, column: 1, maxRank: 5 },
        { id: "ass.improved_poisons", name: "Improved Poisons", iconKey: "improved_poisons", tier: 4, column: 2, maxRank: 5 },
        { id: "ass.cold_blood", name: "Cold Blood", aliases: ["cb"], iconKey: "cold_blood", tier: 5, column: 1, maxRank: 1 },
        { id: "ass.improved_kidney_shot", name: "Improved Kidney Shot", aliases: ["imp ks"], iconKey: "kidney_shot", tier: 5, column: 2, maxRank: 3 },
        { id: "ass.relentless_strikes", name: "Relentless Strikes", iconKey: "relentless_strikes", tier: 6, column: 2, maxRank: 1, prereqId: "ass.improved_slice_and_dice" },
        { id: "ass.vigor", name: "Vigor", iconKey: "vigor", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Combat",
      slug: "combat",
      talents: [
        { id: "combat.improved_gouge", name: "Improved Gouge", iconKey: "gouge", tier: 1, column: 2, maxRank: 3 },
        { id: "combat.improved_sinister_strike", name: "Improved Sinister Strike", aliases: ["imp ss"], iconKey: "sinister_strike", tier: 1, column: 3, maxRank: 2 },
        { id: "combat.lightning_reflexes", name: "Lightning Reflexes", iconKey: "lightning_reflexes_rogue", tier: 2, column: 1, maxRank: 5 },
        { id: "combat.improved_backstab", name: "Improved Backstab", iconKey: "backstab", tier: 2, column: 2, maxRank: 3 },
        { id: "combat.deflection", name: "Deflection", iconKey: "deflection_rogue", tier: 2, column: 3, maxRank: 5 },
        { id: "combat.precision", name: "Precision", iconKey: "precision_rogue", tier: 3, column: 1, maxRank: 5 },
        { id: "combat.endurance", name: "Endurance", iconKey: "endurance", tier: 3, column: 2, maxRank: 2 },
        { id: "combat.riposte", name: "Riposte", iconKey: "riposte", tier: 3, column: 3, maxRank: 1 },
        { id: "combat.improved_sprint", name: "Improved Sprint", iconKey: "sprint", tier: 4, column: 1, maxRank: 2 },
        { id: "combat.improved_kick", name: "Improved Kick", iconKey: "kick", tier: 4, column: 2, maxRank: 2 },
        { id: "combat.dagger_specialization", name: "Dagger Specialization", iconKey: "dagger_specialization", tier: 4, column: 3, maxRank: 5 },
        { id: "combat.dual_wield_specialization", name: "Dual Wield Specialization", aliases: ["dw spec"], iconKey: "dual_wield_specialization", tier: 5, column: 1, maxRank: 5 },
        { id: "combat.mace_specialization", name: "Mace Specialization", iconKey: "mace_specialization", tier: 5, column: 2, maxRank: 5 },
        { id: "combat.blade_flurry", name: "Blade Flurry", iconKey: "blade_flurry", tier: 5, column: 3, maxRank: 1 },
        { id: "combat.sword_specialization", name: "Sword Specialization", aliases: ["sword spec"], iconKey: "sword_specialization", tier: 6, column: 2, maxRank: 5 },
        { id: "combat.fist_weapon_specialization", name: "Fist Weapon Specialization", iconKey: "fist_weapon_specialization", tier: 6, column: 3, maxRank: 5 },
        { id: "combat.weapon_expertise", name: "Weapon Expertise", iconKey: "weapon_expertise", tier: 7, column: 2, maxRank: 2 },
        { id: "combat.adrenaline_rush", name: "Adrenaline Rush", aliases: ["ar"], iconKey: "adrenaline_rush", tier: 7, column: 3, maxRank: 1 },
      ],
    },
    {
      branch: "Subtlety",
      slug: "subtlety",
      talents: [
        { id: "sub.master_of_deception", name: "Master of Deception", aliases: ["mod"], iconKey: "master_of_deception", tier: 1, column: 2, maxRank: 5 },
        { id: "sub.opportunity", name: "Opportunity", iconKey: "opportunity", tier: 1, column: 3, maxRank: 5 },
        { id: "sub.sleight_of_hand", name: "Sleight of Hand", iconKey: "sleight_of_hand", tier: 2, column: 1, maxRank: 2 },
        { id: "sub.elusiveness", name: "Elusiveness", iconKey: "elusiveness", tier: 2, column: 2, maxRank: 5 },
        { id: "sub.camouflage", name: "Camouflage", iconKey: "camouflage", tier: 2, column: 3, maxRank: 5 },
        { id: "sub.initiative", name: "Initiative", iconKey: "initiative", tier: 3, column: 1, maxRank: 3 },
        { id: "sub.ghostly_strike", name: "Ghostly Strike", iconKey: "ghostly_strike", tier: 3, column: 2, maxRank: 1 },
        { id: "sub.improved_ambush", name: "Improved Ambush", iconKey: "ambush", tier: 3, column: 3, maxRank: 3 },
        { id: "sub.setup", name: "Setup", iconKey: "setup", tier: 4, column: 1, maxRank: 3 },
        { id: "sub.improved_sap", name: "Improved Sap", iconKey: "sap", tier: 4, column: 3, maxRank: 3 },
        { id: "sub.serrated_blades", name: "Serrated Blades", iconKey: "serrated_blades", tier: 5, column: 1, maxRank: 3 },
        { id: "sub.heightened_senses", name: "Heightened Senses", iconKey: "heightened_senses", tier: 5, column: 2, maxRank: 2 },
        { id: "sub.preparation", name: "Preparation", aliases: ["prep"], iconKey: "preparation", tier: 6, column: 2, maxRank: 1 },
        { id: "sub.hemorrhage", name: "Hemorrhage", iconKey: "hemorrhage", tier: 7, column: 2, maxRank: 1 },
        { id: "sub.premeditation", name: "Premeditation", iconKey: "premeditation", tier: 7, column: 3, maxRank: 1 },
      ],
    },
  ],
};
