import type { ClassTalents } from "./types";

export const shamanTalents: ClassTalents = {
  classId: "shaman",
  trees: [
    {
      branch: "Elemental",
      slug: "elemental",
      talents: [
        { id: "ele.convection", name: "Convection", iconKey: "convection", tier: 1, column: 2, maxRank: 5 },
        { id: "ele.concussion", name: "Concussion", iconKey: "concussion", tier: 1, column: 3, maxRank: 5 },
        { id: "ele.earths_grasp", name: "Earth's Grasp", iconKey: "earthbind_totem", tier: 2, column: 1, maxRank: 2 },
        { id: "ele.elemental_warding", name: "Elemental Warding", iconKey: "elemental_warding", tier: 2, column: 2, maxRank: 3 },
        { id: "ele.call_of_flame", name: "Call of Flame", iconKey: "fire_totem", tier: 2, column: 3, maxRank: 3 },
        { id: "ele.elemental_focus", name: "Elemental Focus", aliases: ["clearcasting shaman"], iconKey: "elemental_focus", tier: 3, column: 2, maxRank: 1 },
        { id: "ele.reverberation", name: "Reverberation", iconKey: "reverberation", tier: 3, column: 3, maxRank: 5 },
        { id: "ele.improved_fire_totems", name: "Improved Fire Totems", iconKey: "fire_nova_totem", tier: 4, column: 1, maxRank: 2 },
        { id: "ele.elemental_fury", name: "Elemental Fury", iconKey: "elemental_fury", tier: 4, column: 2, maxRank: 1 },
        { id: "ele.improved_lightning_shield", name: "Improved Lightning Shield", iconKey: "lightning_shield", tier: 4, column: 3, maxRank: 5 },
        { id: "ele.eye_of_the_storm", name: "Eye of the Storm", iconKey: "eye_of_the_storm", tier: 5, column: 2, maxRank: 3 },
        { id: "ele.elemental_devastation", name: "Elemental Devastation", iconKey: "elemental_devastation", tier: 5, column: 3, maxRank: 3 },
        { id: "ele.storm_reach", name: "Storm Reach", iconKey: "storm_reach", tier: 6, column: 2, maxRank: 2 },
        { id: "ele.elemental_mastery", name: "Elemental Mastery", aliases: ["em"], iconKey: "elemental_mastery", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Enhancement",
      slug: "enhancement",
      talents: [
        { id: "enh.ancestral_knowledge", name: "Ancestral Knowledge", iconKey: "ancestral_knowledge", tier: 1, column: 2, maxRank: 5 },
        { id: "enh.shield_specialization", name: "Shield Specialization", iconKey: "shield_specialization_shaman", tier: 1, column: 3, maxRank: 5 },
        { id: "enh.guardian_totems", name: "Guardian Totems", iconKey: "tremor_totem", tier: 2, column: 1, maxRank: 2 },
        { id: "enh.thundering_strikes", name: "Thundering Strikes", iconKey: "thundering_strikes", tier: 2, column: 2, maxRank: 5 },
        { id: "enh.improved_ghost_wolf", name: "Improved Ghost Wolf", aliases: ["imp gw"], iconKey: "ghost_wolf", tier: 2, column: 3, maxRank: 2 },
        { id: "enh.improved_lightning_shield", name: "Improved Lightning Shield", iconKey: "lightning_shield", tier: 2, column: 4, maxRank: 3 },
        { id: "enh.enhancing_totems", name: "Enhancing Totems", iconKey: "strength_of_earth", tier: 3, column: 1, maxRank: 2 },
        { id: "enh.two_handed_axes_and_maces", name: "Two-Handed Axes and Maces", aliases: ["2h axes maces"], iconKey: "two_handed_weapon_specialization", tier: 3, column: 2, maxRank: 1 },
        { id: "enh.anticipation", name: "Anticipation", iconKey: "anticipation_shaman", tier: 3, column: 3, maxRank: 5 },
        { id: "enh.flurry", name: "Flurry", iconKey: "flurry", tier: 4, column: 2, maxRank: 5 },
        { id: "enh.improved_weapon_totems", name: "Improved Weapon Totems", iconKey: "windfury_totem", tier: 4, column: 3, maxRank: 2 },
        { id: "enh.elemental_weapons", name: "Elemental Weapons", iconKey: "elemental_weapons", tier: 5, column: 2, maxRank: 3 },
        { id: "enh.parry", name: "Parry", iconKey: "parry", tier: 5, column: 3, maxRank: 1 },
        { id: "enh.weapon_mastery", name: "Weapon Mastery", iconKey: "weapon_mastery", tier: 6, column: 2, maxRank: 5 },
        { id: "enh.stormstrike", name: "Stormstrike", iconKey: "stormstrike", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Restoration",
      slug: "restoration",
      talents: [
        { id: "res.improved_healing_wave", name: "Improved Healing Wave", aliases: ["imp hw"], iconKey: "healing_wave", tier: 1, column: 2, maxRank: 5 },
        { id: "res.tidal_focus", name: "Tidal Focus", iconKey: "tidal_focus", tier: 1, column: 3, maxRank: 5 },
        { id: "res.improved_reincarnation", name: "Improved Reincarnation", iconKey: "reincarnation", tier: 2, column: 1, maxRank: 2 },
        { id: "res.ancestral_healing", name: "Ancestral Healing", iconKey: "ancestral_healing", tier: 2, column: 2, maxRank: 3 },
        { id: "res.totemic_focus", name: "Totemic Focus", iconKey: "totemic_focus", tier: 2, column: 3, maxRank: 5 },
        { id: "res.healing_focus", name: "Healing Focus", iconKey: "healing_focus_shaman", tier: 3, column: 1, maxRank: 5 },
        { id: "res.totemic_mastery", name: "Totemic Mastery", iconKey: "totemic_mastery", tier: 3, column: 3, maxRank: 1 },
        { id: "res.healing_grace", name: "Healing Grace", iconKey: "healing_grace", tier: 4, column: 1, maxRank: 3 },
        { id: "res.restorative_totems", name: "Restorative Totems", iconKey: "mana_spring_totem", tier: 4, column: 2, maxRank: 5 },
        { id: "res.tidal_mastery", name: "Tidal Mastery", iconKey: "tidal_mastery", tier: 5, column: 2, maxRank: 5 },
        { id: "res.healing_way", name: "Healing Way", iconKey: "healing_way", tier: 5, column: 3, maxRank: 3 },
        { id: "res.natures_swiftness", name: "Nature's Swiftness", aliases: ["ns shaman"], iconKey: "natures_swiftness", tier: 6, column: 1, maxRank: 1 },
        { id: "res.purification", name: "Purification", iconKey: "purification", tier: 6, column: 2, maxRank: 5 },
        { id: "res.mana_tide_totem", name: "Mana Tide Totem", aliases: ["mtt"], iconKey: "mana_tide_totem", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
