import type { ClassTalents } from "./types";

export const warlockTalents: ClassTalents = {
  classId: "warlock",
  trees: [
    {
      branch: "Affliction",
      slug: "affliction",
      talents: [
        { id: "aff.suppression", name: "Suppression", iconKey: "suppression", tier: 1, column: 2, maxRank: 5 },
        { id: "aff.improved_corruption", name: "Improved Corruption", iconKey: "corruption", tier: 1, column: 3, maxRank: 5 },
        { id: "aff.improved_curse_of_weakness", name: "Improved Curse of Weakness", aliases: ["imp cow"], iconKey: "curse_of_weakness", tier: 2, column: 1, maxRank: 2 },
        { id: "aff.improved_drain_soul", name: "Improved Drain Soul", iconKey: "drain_soul", tier: 2, column: 2, maxRank: 2 },
        { id: "aff.improved_life_tap", name: "Improved Life Tap", iconKey: "life_tap", tier: 2, column: 3, maxRank: 2 },
        { id: "aff.improved_drain_life", name: "Improved Drain Life", iconKey: "drain_life", tier: 3, column: 1, maxRank: 5 },
        { id: "aff.improved_curse_of_agony", name: "Improved Curse of Agony", aliases: ["imp coa"], iconKey: "curse_of_agony", tier: 3, column: 2, maxRank: 2 },
        { id: "aff.fel_concentration", name: "Fel Concentration", iconKey: "fel_concentration", tier: 3, column: 3, maxRank: 5 },
        { id: "aff.amplify_curse", name: "Amplify Curse", iconKey: "amplify_curse", tier: 4, column: 1, maxRank: 1 },
        { id: "aff.grim_reach", name: "Grim Reach", iconKey: "grim_reach", tier: 4, column: 2, maxRank: 2 },
        { id: "aff.nightfall", name: "Nightfall", iconKey: "nightfall", tier: 5, column: 1, maxRank: 2 },
        { id: "aff.improved_drain_mana", name: "Improved Drain Mana", iconKey: "drain_mana", tier: 5, column: 2, maxRank: 5 },
        { id: "aff.siphon_life", name: "Siphon Life", iconKey: "siphon_life", tier: 5, column: 3, maxRank: 1 },
        { id: "aff.curse_of_exhaustion", name: "Curse of Exhaustion", iconKey: "curse_of_exhaustion", tier: 6, column: 2, maxRank: 1 },
        { id: "aff.dark_pact", name: "Dark Pact", iconKey: "dark_pact", tier: 7, column: 1, maxRank: 1 },
      ],
    },
    {
      branch: "Demonology",
      slug: "demonology",
      talents: [
        { id: "demo.improved_healthstone", name: "Improved Healthstone", iconKey: "healthstone", tier: 1, column: 2, maxRank: 2 },
        { id: "demo.improved_imp", name: "Improved Imp", iconKey: "summon_imp", tier: 1, column: 3, maxRank: 3 },
        { id: "demo.demonic_embrace", name: "Demonic Embrace", iconKey: "demonic_embrace", tier: 2, column: 1, maxRank: 5 },
        { id: "demo.improved_health_funnel", name: "Improved Health Funnel", iconKey: "health_funnel", tier: 2, column: 2, maxRank: 2 },
        { id: "demo.improved_voidwalker", name: "Improved Voidwalker", iconKey: "summon_voidwalker", tier: 2, column: 3, maxRank: 3 },
        { id: "demo.fel_intellect", name: "Fel Intellect", iconKey: "fel_intellect", tier: 3, column: 1, maxRank: 5 },
        { id: "demo.improved_succubus", name: "Improved Succubus", iconKey: "summon_succubus", tier: 3, column: 2, maxRank: 3 },
        { id: "demo.fel_domination", name: "Fel Domination", iconKey: "fel_domination", tier: 3, column: 3, maxRank: 1 },
        { id: "demo.fel_stamina", name: "Fel Stamina", iconKey: "fel_stamina", tier: 4, column: 1, maxRank: 5 },
        { id: "demo.master_summoner", name: "Master Summoner", iconKey: "master_summoner", tier: 4, column: 3, maxRank: 2 },
        { id: "demo.unholy_power", name: "Unholy Power", iconKey: "unholy_power", tier: 5, column: 2, maxRank: 5 },
        { id: "demo.improved_enslave_demon", name: "Improved Enslave Demon", iconKey: "enslave_demon", tier: 6, column: 1, maxRank: 2 },
        { id: "demo.demonic_sacrifice", name: "Demonic Sacrifice", iconKey: "demonic_sacrifice", tier: 6, column: 2, maxRank: 1 },
        { id: "demo.master_demonologist", name: "Master Demonologist", iconKey: "master_demonologist", tier: 6, column: 3, maxRank: 5 },
        { id: "demo.soul_link", name: "Soul Link", iconKey: "soul_link", tier: 7, column: 2, maxRank: 1, prereqId: "demo.demonic_sacrifice" },
      ],
    },
    {
      branch: "Destruction",
      slug: "destruction",
      talents: [
        { id: "destro.improved_shadow_bolt", name: "Improved Shadow Bolt", aliases: ["imp sb", "isb"], iconKey: "shadow_bolt", tier: 1, column: 2, maxRank: 5 },
        { id: "destro.cataclysm", name: "Cataclysm", iconKey: "cataclysm", tier: 1, column: 3, maxRank: 5 },
        { id: "destro.bane", name: "Bane", iconKey: "bane", tier: 2, column: 2, maxRank: 5 },
        { id: "destro.aftermath", name: "Aftermath", iconKey: "aftermath", tier: 2, column: 3, maxRank: 5 },
        { id: "destro.improved_firebolt", name: "Improved Firebolt", iconKey: "firebolt", tier: 3, column: 1, maxRank: 2 },
        { id: "destro.improved_lash_of_pain", name: "Improved Lash of Pain", iconKey: "lash_of_pain", tier: 3, column: 2, maxRank: 2 },
        { id: "destro.devastation", name: "Devastation", iconKey: "devastation", tier: 3, column: 3, maxRank: 5 },
        { id: "destro.shadowburn", name: "Shadowburn", iconKey: "shadowburn", tier: 4, column: 1, maxRank: 1 },
        { id: "destro.intensity", name: "Intensity", iconKey: "intensity", tier: 4, column: 2, maxRank: 2 },
        { id: "destro.destructive_reach", name: "Destructive Reach", iconKey: "destructive_reach", tier: 4, column: 3, maxRank: 2 },
        { id: "destro.improved_searing_pain", name: "Improved Searing Pain", iconKey: "searing_pain", tier: 5, column: 1, maxRank: 5 },
        { id: "destro.pyroclasm", name: "Pyroclasm", iconKey: "pyroclasm", tier: 5, column: 2, maxRank: 2 },
        { id: "destro.improved_immolate", name: "Improved Immolate", iconKey: "immolate", tier: 5, column: 3, maxRank: 5 },
        { id: "destro.ruin", name: "Ruin", iconKey: "ruin", tier: 6, column: 2, maxRank: 1 },
        { id: "destro.emberstorm", name: "Emberstorm", iconKey: "emberstorm", tier: 6, column: 3, maxRank: 5 },
        { id: "destro.conflagrate", name: "Conflagrate", iconKey: "conflagrate", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
