import type { ClassTalents } from "./types";

export const warriorTalents: ClassTalents = {
  classId: "warrior",
  trees: [
    {
      branch: "Arms",
      slug: "arms",
      talents: [
        { id: "arms.improved_heroic_strike", name: "Improved Heroic Strike", aliases: ["imp hs"], iconKey: "heroic_strike", tier: 1, column: 2, maxRank: 3 },
        { id: "arms.deflection", name: "Deflection", iconKey: "deflection_warrior", tier: 1, column: 3, maxRank: 5 },
        { id: "arms.improved_rend", name: "Improved Rend", iconKey: "rend", tier: 2, column: 1, maxRank: 3 },
        { id: "arms.improved_charge", name: "Improved Charge", iconKey: "charge", tier: 2, column: 2, maxRank: 2 },
        { id: "arms.tactical_mastery", name: "Tactical Mastery", iconKey: "tactical_mastery", tier: 2, column: 3, maxRank: 5 },
        { id: "arms.improved_thunder_clap", name: "Improved Thunder Clap", iconKey: "thunder_clap", tier: 3, column: 1, maxRank: 3 },
        { id: "arms.improved_overpower", name: "Improved Overpower", iconKey: "overpower", tier: 3, column: 2, maxRank: 2 },
        { id: "arms.anger_management", name: "Anger Management", iconKey: "anger_management", tier: 3, column: 3, maxRank: 1 },
        { id: "arms.deep_wounds", name: "Deep Wounds", iconKey: "deep_wounds", tier: 4, column: 1, maxRank: 3 },
        { id: "arms.two_handed_weapon_specialization", name: "Two-Handed Weapon Specialization", aliases: ["2h spec warrior"], iconKey: "two_handed_weapon_specialization", tier: 4, column: 2, maxRank: 5 },
        { id: "arms.impale", name: "Impale", iconKey: "impale", tier: 5, column: 1, maxRank: 2 },
        { id: "arms.axe_specialization", name: "Axe Specialization", iconKey: "axe_specialization", tier: 5, column: 2, maxRank: 5 },
        { id: "arms.sweeping_strikes", name: "Sweeping Strikes", iconKey: "sweeping_strikes", tier: 6, column: 1, maxRank: 1 },
        { id: "arms.mace_specialization", name: "Mace Specialization", iconKey: "mace_specialization", tier: 6, column: 2, maxRank: 5 },
        { id: "arms.sword_specialization", name: "Sword Specialization", iconKey: "sword_specialization", tier: 6, column: 3, maxRank: 5 },
        { id: "arms.polearm_specialization", name: "Polearm Specialization", iconKey: "polearm_specialization", tier: 6, column: 4, maxRank: 5 },
        { id: "arms.mortal_strike", name: "Mortal Strike", aliases: ["ms"], iconKey: "mortal_strike", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Fury",
      slug: "fury",
      talents: [
        { id: "fury.booming_voice", name: "Booming Voice", iconKey: "booming_voice", tier: 1, column: 2, maxRank: 5 },
        { id: "fury.cruelty", name: "Cruelty", iconKey: "cruelty", tier: 1, column: 3, maxRank: 5 },
        { id: "fury.improved_demoralizing_shout", name: "Improved Demoralizing Shout", iconKey: "demoralizing_shout", tier: 2, column: 1, maxRank: 5 },
        { id: "fury.unbridled_wrath", name: "Unbridled Wrath", iconKey: "unbridled_wrath", tier: 2, column: 2, maxRank: 5 },
        { id: "fury.improved_cleave", name: "Improved Cleave", iconKey: "cleave", tier: 3, column: 1, maxRank: 3 },
        { id: "fury.piercing_howl", name: "Piercing Howl", iconKey: "piercing_howl", tier: 3, column: 2, maxRank: 1 },
        { id: "fury.blood_craze", name: "Blood Craze", iconKey: "blood_craze", tier: 3, column: 3, maxRank: 3 },
        { id: "fury.improved_battle_shout", name: "Improved Battle Shout", aliases: ["imp bs"], iconKey: "battle_shout", tier: 3, column: 4, maxRank: 5 },
        { id: "fury.dual_wield_specialization", name: "Dual Wield Specialization", aliases: ["dw spec warrior"], iconKey: "dual_wield_specialization_warrior", tier: 4, column: 1, maxRank: 5 },
        { id: "fury.improved_execute", name: "Improved Execute", iconKey: "execute", tier: 4, column: 2, maxRank: 2 },
        { id: "fury.enrage", name: "Enrage", iconKey: "enrage_warrior", tier: 4, column: 3, maxRank: 5 },
        { id: "fury.improved_slam", name: "Improved Slam", iconKey: "slam", tier: 5, column: 2, maxRank: 5 },
        { id: "fury.death_wish", name: "Death Wish", iconKey: "death_wish", tier: 6, column: 2, maxRank: 1 },
        { id: "fury.improved_intercept", name: "Improved Intercept", iconKey: "intercept", tier: 6, column: 3, maxRank: 2 },
        { id: "fury.flurry", name: "Flurry", iconKey: "flurry_warrior", tier: 6, column: 4, maxRank: 5 },
        { id: "fury.bloodthirst", name: "Bloodthirst", aliases: ["bt"], iconKey: "bloodthirst", tier: 7, column: 2, maxRank: 1 },
      ],
    },
    {
      branch: "Protection",
      slug: "protection",
      talents: [
        { id: "prot.improved_bloodrage", name: "Improved Bloodrage", iconKey: "bloodrage", tier: 1, column: 2, maxRank: 2 },
        { id: "prot.tactical_mastery", name: "Tactical Mastery", iconKey: "tactical_mastery", tier: 1, column: 3, maxRank: 5 },
        { id: "prot.shield_specialization", name: "Shield Specialization", iconKey: "shield_specialization_warrior", tier: 2, column: 1, maxRank: 5 },
        { id: "prot.anticipation", name: "Anticipation", iconKey: "anticipation_warrior", tier: 2, column: 2, maxRank: 5 },
        { id: "prot.improved_revenge", name: "Improved Revenge", iconKey: "revenge", tier: 3, column: 1, maxRank: 3 },
        { id: "prot.improved_disarm", name: "Improved Disarm", iconKey: "disarm", tier: 3, column: 2, maxRank: 3 },
        { id: "prot.improved_shield_block", name: "Improved Shield Block", iconKey: "shield_block", tier: 3, column: 3, maxRank: 3 },
        { id: "prot.toughness", name: "Toughness", iconKey: "toughness_warrior", tier: 4, column: 1, maxRank: 5 },
        { id: "prot.improved_shield_wall", name: "Improved Shield Wall", iconKey: "shield_wall", tier: 4, column: 3, maxRank: 2 },
        { id: "prot.concussion_blow", name: "Concussion Blow", iconKey: "concussion_blow", tier: 5, column: 1, maxRank: 1 },
        { id: "prot.improved_taunt", name: "Improved Taunt", iconKey: "taunt", tier: 5, column: 2, maxRank: 2 },
        { id: "prot.improved_shield_bash", name: "Improved Shield Bash", iconKey: "shield_bash", tier: 5, column: 3, maxRank: 3 },
        { id: "prot.one_handed_weapon_specialization", name: "One-Handed Weapon Specialization", aliases: ["1h spec"], iconKey: "one_handed_weapon_specialization", tier: 6, column: 2, maxRank: 5 },
        { id: "prot.shield_slam", name: "Shield Slam", aliases: ["ss"], iconKey: "shield_slam", tier: 7, column: 2, maxRank: 1 },
      ],
    },
  ],
};
